name: Set Board Field Param
description: Assigns the selected value to a sprint board field

inputs:
  PROJECT_NUMBER:
    description: 'Project Number'
  FIELD_NAME:
    description: the name of the field to be changed
  FIELD_VALUE:
    description: the value of the field to be changed
  OWNER:
    description: the owner of the project
  GITHUB_TOKEN:
    description: the github token with the approriate access
runs:

  using: "composite"
  steps:
    - uses: actions/github-script@v6
      with:
        github-token: ${{ inputs.GITHUB_TOKEN }}
        script: |
          const getBoardQuery = `query($owner: String!, $projectNumber: Int!) {
            user(login: $owner) {
              projectV2(number: $projectNumber) {
                id
                items(last: 100, orderBy: {field: POSITION, direction: ASC}) {
                  nodes {
                    databaseId
                    id
                    content {
                      ... on Issue {
                        id
                        number
                      }
                      ... on PullRequest {
                        id
                        number
                      }
                    }
                  }
                }
                fields(first: 20) {
                  nodes {
                    ... on ProjectV2SingleSelectField {
                    id
                    name
                    dataType
                    options {
                      name
                      id
                    }
                  }
                }
              }
            }
          }`

          const queryResult = await github.graphql(getBoardQuery, {
            owner: '${{inputs.OWNER}}',
            projectNumber: parseInt('${{inputs.PROJECT_NUMBER}}')
          })

          const triggerNumber = context.eventName === 'issues' ? context.payload.issue.number : context.payload.pull_request.number


          const selectField = queryResult.user.projectV2.fields.nodes.find((node) => node.name === '${{inputs.FIELD_NAME}}' && node.dataType === 'SINGLE_SELECT')
          const boardItem = queryResult.user.projectV2.items.nodes.find(node => node.content.number === triggerNumber)
          const singleSelectOption = selectField.options.find(option => option.name === '${{inputs.FIELD_VALUE}}')

          const projectId = queryResult.user.projectV2.id
          const itemId = boardItem.id
          const fieldId = selectField.id
          const singleSelectOptionId = singleSelectOption.id


          console.log({projectId,itemId,fieldId,iterationId})

          const assignmentMutationQuery = `mutation($fieldId: ID!, $itemId: ID!, $projectId: ID!, $singleSelectOptionId: String!) {
            updateProjectV2ItemFieldValue(
              input: {projectId: $projectId, itemId: $itemId, fieldId: $fieldId, singleSelectOptionId: {value: $singleSelectOptionId}}
            ) {
            clientMutationId
            }
          }`

          await github.graphql(assignmentMutationQuery,{
            fieldId,
            itemId,
            projectId,
            singleSelectOptionId,
          })

