name: move issue to sprint board
description: moves an issue to a sprintboard

inputs:
  projectNumber:
    description: 'Project Number'
  owner:
    description: the owner of the project
  githubToken:
    description: the github token with the approriate access
runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v6
      with:
        script: |
          const query = `query($owner:String!, $name:String!, $label:String!) {
            repository(owner:$owner, name:$name){
              issues(first:100, labels: [$label]) {
                nodes {
                  id
                }
              }
            }
          }`;
          const variables = {
            owner: context.repo.owner,
            name: context.repo.repo,
            label: 'wontfix'
          }
          const result = await github.graphql(query, variables)
          console.log(result)
