name: move issue to sprint board
description: moves an issue to a sprintboard

inputs:
  PROJECT_NUMBER:
    description: 'Project Number'
  OWNER:
    description: the owner of the project
  GITHUB_TOKEN:
    description: the github token with the approriate access
runs:

  using: "composite"
  steps:
    - uses: actions/github-script@v6
      with:
        script: |
          const getBoardQuery = `query getBoard
              {
                viewer {
                  projectV2(number: parseInt('${{inputs.PROJECT_NUMBER}}') {
                        fields(last: 20) {
                          nodes {
                            ... on ProjectV2Field {
                              id
                              name
                            }
                            ... on ProjectV2IterationField {
                              id
                              name
                            }
                            ... on ProjectV2SingleSelectField {
                              id
                              name
                              options {
                                name
                                id
                              }
                            }
                          }
                        }
                      }
                }
            }`;
          const result = await github.graphql(getBoardQuery)
          console.log({result})

