name: move issue to sprint board
description: moves an issue to a sprintboard

inputs:
  PROJECT_NUMBER:
    description: 'Project Number'
  OWNER:
    description: the owner of the project
  GITHUB_TOKEN:
    description: the github token with the approriate access
runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v6
      with:
        script: |
          console.log(core.getInput('PROJECT_NUMBER'))
          const getBoardQuery = `query getBoard($org: String!, $project_number: Int!) {
              organization(login: $org) {
                projectNext(number: $project_number) {
                  id
                  fields(first: 20) {
                    nodes {
                      id
                      name
                      settings
                    }
                  }
                }
              }
            }`;
          const variables = {
            org: core.getInput('OWNER'),
            project_number: parseInt(core.getInput('PROJECT_NUMBER')),
          }

          const result = await github.graphql(getBoardQuery, variables)
          console.log(result)
