name: move issue to sprint board
description: moves an issue to a sprintboard

inputs:
  PROJECT_NUMBER:
    description: 'Project Number'
  OWNER:
    description: the owner of the project
  GITHUB_TOKEN:
    description: the github token with the approriate access
runs:

  using: "composite"
  steps:
    - uses: actions/github-script@v6
      with:
        github-token: ${{ inputs.GITHUB_TOKEN }}
        script: |
          const getBoardQueryVariables = {
            owner: '${{inputs.OWNER}}',
            projectNumber: parseInt('${{inputs.PROJECT_NUMBER}}')
          }

          const getBoardQuery = `query($owner: String!, $projectNumber: Int!) {
            user(login: $owner) {
              projectV2(number: $projectNumber) {
                id
              }
            }
          }`

          const triggerNumber = context.eventName === 'issues' ? context.payload.issue.number : context.payload.pull_request.number

          const getTriggerIdQuery = `query($repo: String!,$owner: String!, $number: Int!) {
            repository(name: $repo, owner: $owner) {
              issueOrPullRequest(number: $number) {
                ... on Issue { id }
                ... on PullRequest { id }
              }
            }
          }`

          const getBoardQueryResults = await github.graphql(getBoardQuery, getBoardQueryVariables)

          const getTriggerIdQueryResult = await github.graphql(
            getTriggerIdQuery, {
              repo: context.repo.repo,
              owner: context.repo.owner,
              number: triggerNumber
            })

          console.log({getBoardQueryResults, getTriggerIdQueryResult})

          const boardId = getBoardQueryResults.user.projectV2.id
          const ticketId = getTriggerIdQueryResult.repository.issueOrPullRequest.id

          const assignmentMutation = `query($projectId: String!, $contentId: String!) {
            addProjectV2ItemById(input: {projectId: $projectId, contentId: $contentId}) {
              clientMutationId
            }
          }`

          await github.graphql(assignmentMutation,{
            projectId: boardId,
            contentId: ticketId,
          })

          console.log({boardId, ticketId})

