name: move issue to sprint board
description: moves an issue to a sprintboard

inputs:
  REVIEWER_NAMES:
    description: 'Reviewers username separated by a comma'
  GITHUB_TOKEN:
    description: the github token with the approriate access

runs:

  using: "composite"
  steps:
    - uses: actions/github-script@v6
      with:
        github-token: ${{ inputs.GITHUB_TOKEN }}
        script: |



